const Discord = require("discord.js");
const izex= [
    "Anime: [A Silent Voice]",
    "Anime: [One Piece]",
    "Anime: [Cowboy Bebop]",
    "Anime: [Death Note]",
    "Anime: [Attack on Titan]",
    "Anime: [Sailor Moon]",
    "Anime: [Dragon Ball Z]",
    "Anime: [Naruto]",
    "Anime: [Tokyo Ghoul]",
    "Anime: [Monster]",
    "Anime: [Ergo Proxy]",
    "Anime: [Psycho-Pass]",
    "Anime: [Ano Natsu de Matteru]",
    "Anime: [Steins: Gate]",
    "Anime: [Showa Genroku Rakugo Shinjuu]",
    "Anime: [Servamp]",
    "Anime: [Fullmetal Alchemist: Brotherhood]",
    "Anime: [Hunter X Hunter]",
    "Anime: [Code Geass]",
    "Anime: [One Punch Man]",
    "Anime: [Hajime no Ippo]",
    "Anime: [Samurai Champloo]",
    "Anime: [Neon Genesis Evangelion]",
    "Anime: [Great Teacher Onizuka]",
    "Anime: [Slam Dunk]",
    "Anime: [Rurouni Kenshin]",
    "Anime: [Gintama]",
    "Anime: [Erased]",
    "Anime: [Mob Psycho 100]",
    "Anime: [Kuroko no Basket]",
    "Anime: [One Outs]",
    "Anime: [Baccano!]",
    "Anime: [Last Exile]",
    "Anime: [Bleach]",
    "Anime: [Hellsing]",
    "Anime: [Mawaru-Penguindrum]",
    "Anime: [Claymore]",
    "Anime: [Clannad]",
    "Anime: [Vampire Knight]",
    "Anime: [Mirai Nikki +18]",
    "Anime: [Higurashi no Naku Koro ni]",
    "Anime: [Kakegurui]",
    "Anime: [Castlevania]",
    "Anime: [Boku no Hero Academia]",
    "Anime: [Ijaranaide Nagatoro-san]",
    "Anime: [Ouran Koukou Host Club]",
    "Anime: [Demon Slayer]",
    "Anime: [Yarichin Bitch Club +18]",
    "Anime: [Fire Force]",
    "Anime: [Black Clover]",
    "Anime: [Black Butler]",
    "Anime: [The Promised Neverland]",
    "Anime: [Noragami]",
    "Anime: [Kill la Kill +18]",
    "Anime: [Soul Eater]",
    "Anime: [Bunny Girl Senpai",
    "Anime: [Seven Deadly Sins]",
    "Anime: [Sword Art Online]",
    "Anime: [Akame ga Kill]",
    "Anime: [Akudama Drive]",
    "Anime: [Mayo Chiki +18]",
    "Anime: [Aho-girl]",
    "Anime: [Darling in the FranXX]",
    "Anime: [Golden Time]",
    "Anime: [Angel Beats]",
    "Anime: [Shokuge no Soma +18]", 
    "Anime: [3D Kanojo]",
    "Anime: [Nisekoi]",
    "Anime: [Koi to Senkyo to Chocolate]",
    "Anime: [Just Because]",
    "Anime: [xxxHOLİC]",
    "Anime: [Blood Lad]", 
    "Anime: [Sabagebu!]",
    "Anime: [Highschool of the Death]", 
    "Anime: [Classroom of the Elite]",
    "Anime: [5-toubon no Hanayome]", 
    "Anime: [Non Non Biyori]",
    "Anime: [Banana Fish]", 
    "Anime: [Tsurezure Children]",
    "Anime: [Ryuugajou Nanana No Maizoukin]", 
    "Anime: [Dies Irae]",
    "Anime: [Accelerator]", 
    "Anime: [High Score Girl]",
    "Anime: [No Game No Life]",
    "Anime Film: [I want to eat your pancreas]",
    "Anime: [Tengen Toppa Guren Lagann]",
    "Anime Film: [Your Name]",
    "Anime: [Owari No Seraph]",
    "Anime: [Medaka Box]",
    "Anime: [Shiki]",
    "Anime: [Darker Than Black]",
    "Anime: [Devilman Cry Baby]",
    "Anime: [Anohana]",
    "Anime: [Seitokai No Ichizon]",
    "Anime: [Charlotte]",
    "Anime: [Erased]",
    "Anime: [Another]",
    "Anime: [High School DxD +18]",
    "Anime: [Durarara]",
    "Anime: [Toradora]",
    "Anime: [Ghost In The Shield]",
    "Anime: [Dr.Stone]",
    "Anime: [K-project]",
    "Anime: [Re Zero]",
    "Anime: [Date A Live]",
    "Anime: [Macross]",
    "Anime: [Oregairu]",
    "Anime: [Shinmai Maou No Testament +18]",
    "Anime: [Assasination Classroom]",
    "Anime: [Your Lie In April]",
    "Anime: [Eromanga Sensei +18]",
    "Anime: [Tsugumomo]",
    "Anime: [Kaguya-sama: Love Is War]",
    "Anime: [Violet Evergarden]",
    "Anime: [Berserk]",
    "Anime: [Hentai Ouji To Warawanai Neko +18]",
    "Anime: [Elfen Lied]",
    "Anime: [Ao Haru Ride]",
    "Anime: [Deadman Wonderland]",
    "Anime: [Saiki K]",
    "Anime: [Blue Exorcist]",
    "Anime: [Sakura-sou No Pet Na Kanajo]", 
    "Anime: [Senlik Anime Bulamadım!]",
    "Anime: [Senlik Anime Bulamadım!]",
    "Anime: [Senlik Anime Bulamadım!]"
    ];

exports.run = async(client , message, args) =>{
    let tinkie = izex[Math.floor(Math.random() * izex.length)]; 
    const izexlesh = new Discord.MessageEmbed()
    .setColor("#ff0000")
    .setTitle(`*${tinkie}*`)
    .setDescription(`**__Tam senin için izlemelik anime buldum. Şimdiden iyi izlemeler!__**`)
    .setAuthor(`${message.author.tag}`)
    .setThumbnail(`${message.author.avatarURL()}`)

    message.channel.send(izexlesh)

};
exports.conf = {
  enabled: true,
  guildOnly: false,
  aliases: ["anime-öner","animeöner"],
  permLevel: 0
};

exports.help = {
  name: "anime",
  description: "Rasgele Anime Gif Atar!",
  usage: ""
};
//izexlesh
